# Generated by Django 2.0.4 on 2018-04-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
